forge "https://forgeapi.puppetlabs.com"

####################### NOTE #############################
# All modules *must* be pinned to a specific version/tag #
##########################################################

mod 'maxchk/varnish',
  :git => 'https://github.com/maxchk/puppet-varnish.git',
  :ref => 'b998fbfb42207e5614ea0c6a4bf71423c59469b8'
