#!/bin/bash
# Generate random secrets for Mediawiki if they don't already exist

function migrate_db() {
    # Run DB migratation once per mediawiki version

    # Check mediawiki version
    version=$(egrep '$\$wgVersion' DefaultSettings.php | cut -d\' -f2)
    
    oldversion=$(consulate kv get "$kv_prefix/wgVersion")
    if [ -z "$oldversion" -o "$version" != "$oldversion" ]; then

        # Update/set the version in consul so we don't waste time migrating again for this version of mediawiki
        consulate kv set "$kv_prefix/wgVersion" "$version"

        # Migrate the DB
        (cd "$docroot/core"; /usr/bin/php maintenance/update.php --quick)
    fi
}

nubis_project=$(nubis-metadata NUBIS_PROJECT)
nubis_env=$(nubis-metadata NUBIS_ENVIRONMENT)
kv_prefix="$nubis_project-$nubis_env/config"
docroot="/var/www/$nubis_project"

# Generate a new mediawiki secret only if one does not exist
mediawiki_secret=$(consulate kv get "$kv_prefix/SecretKey")
if [ -z "$mediawiki_secret" ]; then
    mediawiki_secret=$(openssl rand -base64 14)
    consulate kv set "$kv_prefix/SecretKey" "$mediawiki_secret"
fi

# Get a exclusive lock from consul so we only run this script once
consul lock "$CONSUL_PREFIX/syncdb" migrate_db()
