#!/bin/sh
# This file is for use on the generic cluster only
# This is really just a hook to the deploy script

if hostname != 'genericadm.private.phx1.mozilla.com'; then
    echo "You probably don't want to run this here."
    exit 0
fi

# Grab the fqdn from the path
NAME=`pwd | cut -d '/' -f 5`

# Call the appropriate deploy script and reload Apache
if [ $NAME == 'wiki-dev.allizom.org' ]; then
    /data/genericrhel6-dev/deploy wiki-dev.allizom.org
    issue-multi-command genericrhel6-dev service httpd graceful
elif  [ $NAME == 'wiki.allizom.org' ]; then
    /data/genericrhel6-dev/deploy wiki.allizom.org
    issue-multi-command genericrhel6-stage service httpd graceful
elif  [ $NAME == 'wiki.mozilla.org' ]; then
    /data/genericrhel6-dev/deploy wiki.mozilla.org
    issue-multi-command genericrhel6 service httpd graceful
else
    echo "ERROR: Can not match directory"
    exit 1
fi

# eof